server:
  context-path: /edu
  port: 8080

spring:
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/edudb?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver

    sqlserver:
      url=jdbc:sqlserver://192.168.x.xxx:1433;database=edudb
