spring:
  profiles:
    active: lnz
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/edudb?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 12548970
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  context-path: /edu
  port: 8080
